import { ShipType } from 'types/game-types'

type ShipsFunc = () => ShipType[]

export const getDefaultShips: ShipsFunc = () => [
  /*
          placed - флаг, который показывает, стоит ли корабль на игровом поле.
          Если он false, значит корабль ещё в доке.
      */
  {
    id: 1,
    x: 2,
    y: 0,
    length: 4,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 2,
    x: 0,
    y: 2,
    length: 3,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 3,
    x: 5,
    y: 2,
    length: 3,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 4,
    x: 0,
    y: 4,
    length: 2,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 5,
    x: 3,
    y: 4,
    length: 2,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 6,
    x: 6,
    y: 4,
    length: 2,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 7,
    x: 0,
    y: 6,
    length: 1,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 8,
    x: 2,
    y: 6,
    length: 1,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 9,
    x: 4,
    y: 6,
    length: 1,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
  {
    id: 10,
    x: 8,
    y: 7,
    length: 1,
    direction: 'row',
    placed: false,
    range: [],
    destructure: 0,
  },
]
